#!/bin/bash

S3_URI= “ Path to your sql file “ 
RDS_ENDPOINT= “ Input your RDS Address “
RDS_DB_NAME= “DB Name “ 
RDS_DB_USERNAME= “ Username created by You” 
RDS_DB_PASSWORD=“ Password set by You “ 

# Update all packages
S3_URI=“ Path to your sql file “ 
RDS_ENDPOINT= “ Input your RDS Address “
RDS_DB_NAME=“DB Name “ 
RDS_DB_USERNAME=“ Username created by You” 
RDS_DB_PASSWORD=“ Password set by You “ 

Run 
# sudo yum update -y


# Download and extract Flyway
sudo wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.9.1/flyway-commandline-10.9.1-linux-x64.tar.gz | tar -xvz 

# Create a symbolic link to make Flyway accessible globally
sudo ln -s $(pwd)/flyway-10.9.1/flyway /usr/local/bin

# Create the SQL directory for migrations
sudo mkdir sql

# Download the migration SQL script from AWS S3
sudo aws s3 cp "$S3_URI" sql/

# Run Flyway migration
flyway -url=jdbc:mysql://"$RDS_ENDPOINT":3306/"$RDS_DB_NAME" \
  -user="$RDS_DB_USERNAME" \
  -password="$RDS_DB_PASSWORD" \
  -locations=filesystem:sql \
  migrate
